#if !defined(_radio_limits_H)
# define _radio_limits_H (1)

#define KR_RADIO_CLIENTS_MAX 128

#define KR_MIXER_NPATHS 16

#define KR_XFER_NPATHS KR_RADIO_CLIENTS_MAX
#define KR_TRANSMIT_CLIENTS_MAX 64

#define KR_WEB_NPATHS KR_RADIO_CLIENTS_MAX

#define KR_XPDR_NPATHS 16

#define KR_TRACKER_NTRACKS 16
#define KR_TRACK_NRDHEADS 64
#define KR_TRACK_NWRHEADS 4
#define KR_TRACK_NHEADS KR_TRACK_NRDHEADS + KR_TRACK_NWRHEADS
#define KR_TRACK_NSECTORS 1

#define KR_STUDIO_NPATHS 16
#define KR_STUDIO_NPROCS 16
#define KR_DEMUXER_NTRACKS 1

#endif
